name: econaga_prj
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.1
  animated_text_kit: ^4.2.1
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  cached_network_image: ^3.3.1
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.8
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  get: ^4.6.6
  image_picker: ^1.1.2
  firebase_storage: ^12.2.0
  carousel_slider: ^5.0.0
  flutter_polyline_points: ^2.1.0
  google_maps_flutter: ^2.6.1
  google_places_flutter: ^2.0.9
  geolocator: ^7.0.3
  geocoding: ^2.0.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0



flutter:
  uses-material-design: true

  assets:
    - lib/components/assets/images/
    - lib/components/assets/


flutter_launcher_icons:
  android: true
  image_path: "lib/components/assets/images/official_logo.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "lib/common/assets/images/logo.png"
    icon_size: 48
    background_color: "#FFFFFF"
