// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyykBKHZVOG16WLaKbK3EqOfGPeSoLfFw',
    appId: '1:451051198012:web:ce4e9122aff5868d5bd539',
    messagingSenderId: '451051198012',
    projectId: 'econaga-proj',
    authDomain: 'econaga-proj.firebaseapp.com',
    storageBucket: 'econaga-proj.appspot.com',
    measurementId: 'G-Z07CGPY16P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK301cXJ3GjpebxgQemP7mmQcNfTLzm5w',
    appId: '1:451051198012:android:48d3991644723ea75bd539',
    messagingSenderId: '451051198012',
    projectId: 'econaga-proj',
    storageBucket: 'econaga-proj.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyykBKHZVOG16WLaKbK3EqOfGPeSoLfFw',
    appId: '1:451051198012:web:ec4dc36706cef5f85bd539',
    messagingSenderId: '451051198012',
    projectId: 'econaga-proj',
    authDomain: 'econaga-proj.firebaseapp.com',
    storageBucket: 'econaga-proj.appspot.com',
    measurementId: 'G-Z74860F644',
  );
}
